username: postgres
password: password
database_name:
  development: development_db
  staging: development_db
  production: development_db
  test: development_db
deploy_path: '/'
server_ip: localhost
deploy_user: user_deploy
