require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AboutMesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AboutMe. As you add validations to AboutMe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AboutMesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all about_mes as @about_mes" do
      about_me = AboutMe.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:about_mes)).to eq([about_me])
    end
  end

  describe "GET show" do
    it "assigns the requested about_me as @about_me" do
      about_me = AboutMe.create! valid_attributes
      get :show, {:id => about_me.to_param}, valid_session
      expect(assigns(:about_me)).to eq(about_me)
    end
  end

  describe "GET new" do
    it "assigns a new about_me as @about_me" do
      get :new, {}, valid_session
      expect(assigns(:about_me)).to be_a_new(AboutMe)
    end
  end

  describe "GET edit" do
    it "assigns the requested about_me as @about_me" do
      about_me = AboutMe.create! valid_attributes
      get :edit, {:id => about_me.to_param}, valid_session
      expect(assigns(:about_me)).to eq(about_me)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AboutMe" do
        expect {
          post :create, {:about_me => valid_attributes}, valid_session
        }.to change(AboutMe, :count).by(1)
      end

      it "assigns a newly created about_me as @about_me" do
        post :create, {:about_me => valid_attributes}, valid_session
        expect(assigns(:about_me)).to be_a(AboutMe)
        expect(assigns(:about_me)).to be_persisted
      end

      it "redirects to the created about_me" do
        post :create, {:about_me => valid_attributes}, valid_session
        expect(response).to redirect_to(AboutMe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved about_me as @about_me" do
        post :create, {:about_me => invalid_attributes}, valid_session
        expect(assigns(:about_me)).to be_a_new(AboutMe)
      end

      it "re-renders the 'new' template" do
        post :create, {:about_me => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested about_me" do
        about_me = AboutMe.create! valid_attributes
        put :update, {:id => about_me.to_param, :about_me => new_attributes}, valid_session
        about_me.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested about_me as @about_me" do
        about_me = AboutMe.create! valid_attributes
        put :update, {:id => about_me.to_param, :about_me => valid_attributes}, valid_session
        expect(assigns(:about_me)).to eq(about_me)
      end

      it "redirects to the about_me" do
        about_me = AboutMe.create! valid_attributes
        put :update, {:id => about_me.to_param, :about_me => valid_attributes}, valid_session
        expect(response).to redirect_to(about_me)
      end
    end

    describe "with invalid params" do
      it "assigns the about_me as @about_me" do
        about_me = AboutMe.create! valid_attributes
        put :update, {:id => about_me.to_param, :about_me => invalid_attributes}, valid_session
        expect(assigns(:about_me)).to eq(about_me)
      end

      it "re-renders the 'edit' template" do
        about_me = AboutMe.create! valid_attributes
        put :update, {:id => about_me.to_param, :about_me => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested about_me" do
      about_me = AboutMe.create! valid_attributes
      expect {
        delete :destroy, {:id => about_me.to_param}, valid_session
      }.to change(AboutMe, :count).by(-1)
    end

    it "redirects to the about_mes list" do
      about_me = AboutMe.create! valid_attributes
      delete :destroy, {:id => about_me.to_param}, valid_session
      expect(response).to redirect_to(about_mes_url)
    end
  end

end
